# -*- coding: utf-8 -*-
"""numpy_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GTlFvrE5zzhxHQa4_kj5OXcEJomneP_
"""



"""# NumPy

"""

import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b.shape)

c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

"""Initial placeholders"""

#create np array with zeros

x = np.zeros((4,5))
print(x)

#create a matrix with ones
y = np.ones((3,3))
print(y)

#create matrix with a specific value
z = np.full((5,4), 5)
print(z)

#create identity matrix

id = np.eye(4)
print(id)

#create numpy array with random values

b = np.random.random((3, 4))
print(b)

#create numpy random integer value array

c = np.random.randint(10, 100, (3,5))
print(c)

# evenly spaced values -> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

#evenly spaced values with step value
e = np.arange(10, 30,6)
print(e)

list2 = [10,30,35,40]
nls = np.asarray(list2)
print(nls)
print(type(nls))

"""Analysing a numpy array"""

c = np.random.randint(40, 100, (5,5))
print(c)

# get dimension
print(c.shape)

print(c.ndim) ## 2 d array

print(c.size) ##get the size of array

print(c.dtype) #get data type of values in array

"""Mathematical operations on a np array"""

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2)

print('#######')
a = np.random.randint(1,10,(3,3))
b = np.random.randint(30,40,(3,3))

print(a)
print(b)

print(a+b)
print(a*b)
print(a-b)

"""Array manipulation"""

a = np.random.randint(0,10,(2,3))
print(a)

#transpose

trans = np.transpose(a)
print(trans)
print(trans.shape)

#transpose
trans2 = a.T
print(trans2)
print(trans2.shape)

#reshaping array
a = np.random.randint(0,10,(2,3))
print(a.shape)
print(a)

b = a.reshape(3,2)
print(b)
print(b.shape)